# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'djkna' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for djkna
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 2.3'

  target 'djkna-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'djknaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
